#!/bin/bash

display_menu() {
	echo "Make your selection:
	1) Display memory usage
	2) Display disk usage
	3) Display network usage
	4) Quit"

}

display_mem() {
	echo "Memory usage:";
	free -h | grep -v +;
}

display_disk() {
	echo "Disk usage:";
	df -h | grep -v "tmpfs" | grep -v "run" | grep -v "dev ";
}

display_network() {
	hn=$(hostname);
	iip=$(ip add | grep "inet" | grep -v "127.0" | grep -v "inet6" | awk "{print \$2}");
	eip=$(wget -qO- http://ipecho.net/plain | xargs echo);
	echo "Network usage:";
	echo "Hostname: $hn";
	echo "Internal IP: $iip";
	echo "External IP: $eip";
}

echo "Welcome to MStat";
while true; do
	display_menu;
	read sel;
	case $sel in
		1)
			display_mem
			;;
		2)
			display_disk
			;;
		3)
			display_network
			;;
		4)
			echo "Quitting."
			break;;
		*)
			echo "Invalid command."
			exit 1
			;;
	esac;
done;
