#!/bin/bash

display_menu() {
	echo "Make your selection:
	1) Display memory usage
	2) Display disk usage
	3) Display network usage
	4) Quit"

}

display_mem() {
	echo "Memory usage:";
}

display_disk() {
	echo "DIsk usage:";
}

display_network() {
	echo "Network usage:";
}

echo "Welcome to MStat";
while true; do
	display_menu;
	read sel;
	case $sel in
		1)
			display_mem
			;;
		2)
			display_disk
			;;
		3)
			display_network
			;;
		4)
			echo "Quitting."
			break;;
		*)
			echo "Invalid command."
			exit 1
			;;
	esac;
done;
